import NMPNativeRuntime

public typealias NativeRuntimeAccountFailure = RuntimeAccountFailure
public typealias NativeRuntimeAccountHandle = RuntimeAccountHandle
public typealias NativeRuntimeAccountKind = RuntimeAccountKind
public typealias NativeRuntimeAccountSnapshot = RuntimeAccountSnapshot
public typealias NativeRuntimeAccountUpdate = RuntimeAccountUpdate

public typealias NativeRuntimeCatalogCancellationResult =
    RuntimeCatalogCancellationResult
public typealias NativeRuntimeCatalogCapability = RuntimeCatalogCapability
public typealias NativeRuntimeCatalogConfirmation = RuntimeCatalogConfirmation
public typealias NativeRuntimeCatalogEntry = RuntimeCatalogEntry
public typealias NativeRuntimeCatalogFailure = RuntimeCatalogFailure
public typealias NativeRuntimeCatalogFeedSnapshot = RuntimeCatalogFeedSnapshot
public typealias NativeRuntimeCatalogInstallEligibility =
    RuntimeCatalogInstallEligibility
public typealias NativeRuntimeCatalogLookupState = RuntimeCatalogLookupState
public typealias NativeRuntimeCatalogPage = RuntimeCatalogPage
public typealias NativeRuntimeCatalogPageResult = RuntimeCatalogPageResult
public typealias NativeRuntimeCatalogProvenance = RuntimeCatalogProvenance
public typealias NativeRuntimeCatalogReview = RuntimeCatalogReview
public typealias NativeRuntimeCatalogReviewResult = RuntimeCatalogReviewResult
public typealias NativeRuntimeCatalogShortfall = RuntimeCatalogShortfall
public typealias NativeRuntimeCatalogSource = RuntimeCatalogSource
public typealias NativeRuntimeCatalogSourceAccess = RuntimeCatalogSourceAccess
public typealias NativeRuntimeCatalogSourceState = RuntimeCatalogSourceState
public typealias NativeRuntimeCatalogWindowState = RuntimeCatalogWindowState

public typealias NativeRuntimeRelayAccess = RuntimeRelayAccess
public typealias NativeRuntimeRelayCoverage = RuntimeRelayCoverage
public typealias NativeRuntimeRelayDiagnostics = RuntimeRelayDiagnostics
public typealias NativeRuntimeRelayDiagnosticsSnapshot =
    RuntimeRelayDiagnosticsSnapshot
public typealias NativeRuntimeRelayKindCount = RuntimeRelayKindCount
public typealias NativeRuntimeRelayLane = RuntimeRelayLane
public typealias NativeRuntimeRelayLaneCount = RuntimeRelayLaneCount
public typealias NativeRuntimeRelaySubscription = RuntimeRelaySubscription

public typealias NativeRuntimeWorkspaceAxis = RuntimeWorkspaceAxis
public typealias NativeRuntimeWorkspaceDefinition = RuntimeWorkspaceDefinition
public typealias NativeRuntimeWorkspaceRenderer = RuntimeWorkspaceRenderer
public typealias NativeRuntimeWorkspaceRestore = RuntimeWorkspaceRestore
public typealias NativeRuntimeWorkspaceRole = RuntimeWorkspaceRole
public typealias NativeRuntimeWorkspaceSlot = RuntimeWorkspaceSlot
public typealias NativeRuntimeWorkspaceUpdate = RuntimeWorkspaceUpdate
public typealias NativeRuntimePermissionMode = RuntimePermissionMode
